version: "3.4"

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB= store_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      target: production
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      postgres